# Generated by Django 2.1.2 on 2018-10-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Brandy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('kodtowaru', models.CharField(db_column='kodTowaru', max_length=128, primary_key=True, serialize=False)),
                ('kontrahentkod', models.CharField(db_column='kontrahentKod', max_length=64)),
                ('kontrahentcennik', models.CharField(db_column='kontrahentCennik', max_length=16)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
                ('gruparabatowa_1', models.CharField(blank=True, db_column='grupaRabatowa_1', max_length=64, null=True)),
                ('gruparabatowa_2', models.CharField(blank=True, db_column='grupaRabatowa_2', max_length=64, null=True)),
                ('gruparabatowa_3', models.CharField(blank=True, db_column='grupaRabatowa_3', max_length=64, null=True)),
                ('cenakatalogowa', models.DecimalField(blank=True, db_column='cenaKatalogowa', decimal_places=4, max_digits=12, null=True)),
                ('walutakatalogowa', models.CharField(blank=True, db_column='walutaKatalogowa', max_length=3, null=True)),
                ('cenakoncowa', models.DecimalField(blank=True, db_column='cenaKoncowa', decimal_places=4, max_digits=12, null=True)),
                ('walutakoncowa', models.CharField(blank=True, db_column='walutaKoncowa', max_length=3, null=True)),
                ('cenakatalogowa_eur', models.DecimalField(blank=True, db_column='cenaKatalogowa_EUR', decimal_places=4, max_digits=12, null=True)),
                ('cenakoncowa_eur', models.DecimalField(blank=True, db_column='cenaKoncowa_EUR', decimal_places=4, max_digits=12, null=True)),
                ('moq', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('dataimportu', models.DateField(db_column='dataImportu')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porownanie_cen.Brand')),
            ],
            options={
                'db_table': 'Produkty',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='produkt',
            unique_together={('kodtowaru', 'kontrahentkod', 'kontrahentcennik')},
        ),
    ]
