# Generated by Django 2.1.2 on 2018-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0002_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
