# Generated by Django 2.1.2 on 2018-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0002_remove_produkt_klucz'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='klucz',
            field=models.CharField(db_column='klucz', default='django', max_length=128),
        ),
    ]
