# Generated by Django 2.1.2 on 2018-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0003_auto_20181019_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='dataimportu',
            field=models.DateField(auto_now_add=True, db_column='dataImportu'),
        ),
    ]
