# Generated by Django 2.1.2 on 2018-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0005_auto_20181107_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.CharField(db_column='icon', default='fas fa-rocket fa-9x', max_length=200),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='klucz',
            field=models.CharField(db_column='klucz', max_length=128),
        ),
    ]
