# Generated by Django 2.1.2 on 2018-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0005_auto_20181019_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
