# Generated by Django 2.1.2 on 2018-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0006_auto_20181116_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.CharField(db_column='icon', default='fas fa-rocket fa-5x', max_length=200),
        ),
    ]
