# Generated by Django 2.1.2 on 2018-10-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0006_auto_20181019_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_column='nazwa', max_length=200),
        ),
    ]
