# Generated by Django 2.1.2 on 2018-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0007_auto_20181019_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='nazwa',
        ),
    ]
