# Generated by Django 2.1.2 on 2018-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0008_auto_20181019_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='opis',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
