# Generated by Django 2.1.2 on 2018-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0009_auto_20181019_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
