# Generated by Django 2.1.2 on 2018-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porownanie_cen', '0011_auto_20181019_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
